module.exports = {
  name: "James Christensen LMFT",
  practice: "Roseville Couples Counseling",
  license: "#142990",
  url: "https://jamesmchristensen.com",
  description:
    "Couples therapy and marriage counseling in Roseville, CA for conflict, disconnection, infidelity, and communication problems. First session free.",
  phoneDisplay: "916-292-8920",
  phoneTel: "tel:9162928920",
  booking: "https://james.clientsecure.me/request/service",
  address: ["300 Harding Blvd, Suite 108", "Roseville, CA 95678"],
  ga: "G-FL14YETXQW",
  gtm: "GTM-TLB6DLP9",
  pixel: "523134667361670",
  facebookDomainVerification: "6trlgtc8wro0905iwbk9ha5nms0ms4",
  services: [
    { href: "/intensive-couples-therapy/", label: "Intensive Couples Therapy" },
    { href: "/private-couples-retreats/", label: "Private Marriage Retreats" },
    { href: "/codependency/", label: "Codependency" },
    { href: "/communication/", label: "Communication" },
    { href: "/disconnection/", label: "Disconnection" },
    { href: "/infidelity/", label: "Infidelity" },
    { href: "/intimacy-and-desire/", label: "Dead Bedroom" },
    { href: "/narcissism/", label: "Narcissism" },
    { href: "/relationship-anxiety/", label: "Relationship Anxiety" },
    { href: "/threats-of-divorce/", label: "Threats of Divorce" },
  ],
  resources: [
    { href: "/blog/", label: "Blog" },
    { href: "/faq/", label: "FAQ" },
    { href: "/podcast/", label: "Podcast" },
    { href: "/videos/", label: "Videos" },
    { href: "/contact/", label: "Contact" },
    { href: "/read/", label: "Reading List" },
    { href: "/book-summaries/", label: "Book Summaries" },
    { href: "/crucible/", label: "About Crucible Therapy" },
    { href: "/about-james-christensen/", label: "About James Christensen" },
    { href: "/david-schnarch/", label: "About David Schnarch" },
    { href: "/how-couples-therapy-works/", label: "How Couples Therapy Works" },
    { href: "/newsletter/", label: "Email list" },
    { href: "/privacy/", label: "Privacy" },
  ],
};
